# Generated by BehavEd
# ( "Omega1 Zonescript" )
firstIN = getGameFlag("omega1", 11 )
if firstIN == 0
     setGameFlag("omega1", 11, 1 )
     startConversation("act1/omega/omega1/1_OMEGA1_010" )
endif
obj = getGameVar("o1gears" )
if obj == 1
     remove ( "wreck", "wreck" )
     act("act_gears", "act_gears" )
     gear1 = getGameFlag("omega1gears", 1 )
     if gear1 == 1
          swapInStump("gear1" )
          remove ( "gear1_ht", "gear1_ht" )
     endif
     gear2 = getGameFlag("omega1gears", 2 )
     if gear2 == 1
          swapInStump("gear2" )
          remove ( "gear2_ht", "gear2_ht" )
     endif
     gear3 = getGameFlag("omega1gears", 3 )
     if gear3 == 1
          swapInStump("gear3" )
          remove ( "gear3_ht", "gear3_ht" )
     endif
     gear4 = getGameFlag("omega1gears", 4 )
     if gear4 == 1
          swapInStump("gear4" )
          remove ( "gear4_ht", "gear4_ht" )
     endif
endif
dum = getGameFlag("omega1", 1 )
if dum == 1
     beATeamPlayer("dugan", "TRUE" )
     showHealthBar("dugan", "TRUE" )
     setHintType("dugan", "objective" )
     dum2 = getGameFlag("omega1", 2 )
     if dum2 == 1
          setGameVar("omega1dugan", 5 )
          showHealthBar("crimdugan", "TRUE" )
          setHintType("crimdugan", "objective" )
          teamplayer = getGameFlag("omega1", 3 )
          if teamplayer == 1
               beATeamPlayer("crimdugan", "TRUE" )
          endif
     endif
endif
dugandone = getObjective("omega_obj20", "COMPLETE" )
if dugandone == 1
     remove ( "trigger_meet_dum", "trigger_meet_dum" )
     remove ( "trigger_cr", "trigger_cr" )
     remove ( "endcrm", "endcrm" )
     remove ( "crimdugan_spawn", "crimdugan_spawn" )
endif

