# Generated by BehavEd
# ( "does the player have the combination to open the safe?" )
combo = getGameFlag("atlantis2", 7 )
if combo == 0
     # ( "player doesn't have combination--give a hint" )
     startConversation("act1/atlantis/atlantis2/1_atlantis2_080" )
else
     # ( "player has combination--remove triggers and dispense treasure" )
     remove ( "trig_safe", "trig_safe" )
     act("safe", "safe" )
     sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
     createPopupDialogXml("dialogs/special/atlantis_chest_achievement" )
     # ( "PERSISTENCE--indicate safe has been opened" )
     setGameFlag("atlantis2", 8, 1 )
     setEnable("daredevil_af", "TRUE" )
     act("theloot", "theloot" )
endif

