# Generated by BehavEd
# ( "is this the first time an inducer has been destroyed?" )
inducer = getGameFlag("atlantis2", 3 )
if inducer == 0
     # ( "this is the first time an inducer is destroyed--start conversation" )
     # ( "PERSISTENCE--indicate an inducer has been destroyed for the first time" )
     setGameFlag("atlantis2", 3, 1 )
endif
# ( "PERSISTENCE--indicate inducer3 has been destroyed" )
setGameFlag("atlantis2", 6, 1 )
objective ( "atlantis_obj30",  "EOBJCMD_INCREMENT" )
# ( "is this the last of the inducers?" )
inducer = getObjective("atlantis_obj30", "COMPLETE" )
if inducer == 1
     # ( "all inducers are destroyed--celebrate with a victory conversation" )
     waittimed ( 0.100 )
     awardXPToPlayable(5000 )
     sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
     createPopupDialogXml("dialogs/special/sonic_emitters_achievement" )
     waittimed ( 0.100 )
     startConversation("act1/atlantis/atlantis2/1_atlantis2_040" )
     objective ( "atlantis_obj30",  "EOBJCMD_COMPLETE" )
endif

