# Generated by BehavEd
# ( "found ring, volla appears, conversation ensues." )
key = getGameFlag("niffleheim1", 5 )
if key == 1
     setGameFlag("niffleheim1", 6, 1 )
     # ( "TEMPVOLLA != Volla. Replace her." )
     act("ring_chest", "ring_chest" )
     act("TEMPVOLLA2", "TEMPVOLLA2" )
     waittimed ( 0.250 )
     fade("volla", 1.000, 0.000, "FALSE" )
     startCutScene("FALSE", "FALSE" )
     cameraFocusToEntity("volla", 400.000, 25.000, 180.000, 1.000 )
     waittimed ( 0.250 )
     fade("volla", 0.000, 1.000, "FALSE" )
     waittimed ( 1.000 )
     sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
     createPopupDialogXml("dialogs/special/vollaring_achievement" )
     waittimed ( 0.100 )
     startCharConversation("act3/niffleheim/niffleheim1/3_niffleheim1_050", "blade", "act3/niffleheim/niffleheim1/3_niffleheim1_052" )
else
     display ( "This shouldn't happen." )
endif

