# Generated by BehavEd
# ( "common drilldeath stuff" )
objective ( "Skrull_Obj20",  "EOBJCMD_INCREMENT" )
drills = getObjective("Skrull_Obj20", "COUNT" )
if drills == 2
     objective ( "Skrull_Obj20",  "EOBJCMD_COMPLETE" )
     waittimed ( 0.100 )
     sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
     createPopupDialogXml("dialogs/special/skrulldrills_achievement" )
     waittimed ( 0.100 )
     setEpilogue(9, 1 )
     startConversation("act4/skrull/skrull3/4_skrull3_030" )
endif
# ( "specialized for each drill" )
spawnEffect("drill1", "base/material/explode/exp_generic_lrg", " 0.000 0.000 1200.000 ", " 0.000 0.000 0.000 " )
waittimed ( 0.250 )
spawnEffect("drill1", "base/material/explode/exp_generic_lrg", " 0.000 0.000 1000.000 ", " 0.000 0.000 0.000 " )
waittimed ( 0.250 )
spawnEffect("drill1", "base/material/explode/exp_generic_lrg", " 0.000 0.000 800.000 ", " 0.000 0.000 0.000 " )
waittimed ( 0.250 )
spawnEffect("drill1", "base/material/explode/exp_generic_lrg", " 0.000 0.000 600.000 ", " 0.000 0.000 0.000 " )

