# Generated by BehavEd
# ( "Baron Mordo deathscript" )
waittimed ( 0.100 )
unlockCharacter("mordo", "" )
waittimed ( 0.100 )
unlockCharacter("ultro", "" )
waittimed ( 0.100 )
unlockCharacter("sentinel", "" )
awardReputation("", 20 )
setGameFlag("niffleheim3", 4, 1 )
var = getGameFlag("niffleheim3", 5 )
if var == 1
     act("vill_defeat", "vill_defeat" )
endif

