# Generated by BehavEd
# ( "Loki 1 dies" )
# ( "kill all frost giants" )
waittimed ( 0.100 )
sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
createPopupDialogXml("dialogs/special/loki2_achievement" )
waittimed ( 0.100 )
unlockCharacter("odin", "" )
waittimed ( 0.100 )
unlockCharacter("lokih", "" )
killEntity("frosty" )
waittimed ( 3.000 )
startConversation("act3/niffleheim/niffleheim4/3_niffleheim4_020" )

