# Generated by BehavEd
# ( "is the activator using dark thor's hammer?" )
hammer = strcatstr("dark_hammer", "" )
held_weapon = getHeldWeapon("_ACTIVATOR_" )
if hammer == held_weapon
     # ( "dark thor's hammer is being used--destroy Odin's prison" )
     killEntity("dark_machine" )
     act("fx_mach_blast", "fx_mach_blast" )
     cameraFocusToEntity("odin", 384.000, 45.000, 180.000, 2.000 )
     waittimed ( 2.000 )
     # ( "PERSISTENCE--indicate Odin has been freed" )
     setGameFlag("doom4", 4, 1 )
     awardReputation("", 20 )
     objective ( "doom_obj50",  "EOBJCMD_COMPLETE" )
     waittimed ( 0.100 )
     sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
     createPopupDialogXml("dialogs/special/saveodin_achievement" )
     waittimed ( 0.100 )
     setEpilogue(10, 1 )
     startConversation("act5/doom/doom4/5_DOOM4_200" )
else
     # ( "is this the first time the machine has been attacked?" )
     check = getZoneVar("mach_pain" )
     if check == 0
          # ( "this is the first time the machine has been attacked..." )
          # ( "...start conversation hint" )
          startConversation("act5/doom/doom4/5_DOOM4_170" )
          # ( "indicate the machine has been attacked, and a hint given" )
          setZoneVar("mach_pain", 1 )
     endif
endif

