# Generated by BehavEd
# ( "comment" )
waittimed ( 0.100 )
sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
createPopupDialogXml("dialogs/special/nullifier_achievement" )
waittimed ( 0.100 )
startConversation("act5/doom/doom4/5_doom4_020" )

