# Generated by BehavEd
# ( "indicate senator kelly has been rescued" )
objective ( "murder_obj30",  "EOBJCMD_COMPLETE" )
setEpilogue(3, 1 )
waittimed ( 0.100 )
sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
createPopupDialogXml("dialogs/special/kelly_achievement" )
waittimed ( 0.100 )
# ( "start conversation" )
startCharConversation("act2/murder/murder2/2_murder2_075", "storm", "act2/murder/murder2/2_murder2_077" )

