# Generated by BehavEd
# ( "comment" )
cameraSetClipPlane(17000.000 )
bi1_3 = getObjective("bifrost_obj20", "COMPLETE" )
waittimed ( 0.100 )
sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
createPopupDialogXml("dialogs/special/dragonfang_achievement" )
waittimed ( 0.100 )
if bi1_3 ==  1
     remove ( "u_valkyrie_sword_bi_e01", "u_valkyrie_sword_bi_e01" )
     remove ( "trigger_val", "trigger_val" )
endif
bi1 = getGameFlag("bifrost1", 1 )
if bi1 ==  1
     setGameFlag("bifrost1", 1, 1 )
     objective ( "bifrost_obj0",  "EOBJCMD_SHOW" )
     objective ( "bifrost_obj10",  "EOBJCMD_SHOW" )
endif
bi1_2 = getGameFlag("bifrost1", 2 )
if bi1_2 ==  0
     # ( "first in the zone check" )
     setGameFlag("bifrost1", 2, 1 )
     startConversation("act3/bifrost/bifrost1/3_bifrost1_010" )
endif

