# Generated by BehavEd
# ( "comment" )
cameraFade(1.000, 0.100 )
waittimed ( 0.100 )
cameraSetClipPlane(17500.000 )
use ( "ss_shiartracker_a15", "ss_shiartracker_a15" )
use ( "ss_shiartracker_a09", "ss_shiartracker_a09" )
use ( "ss_shiartracker_a08", "ss_shiartracker_a08" )
use ( "ss_shiartracker_a12", "ss_shiartracker_a12" )
use ( "ss_shiartracker_a01", "ss_shiartracker_a01" )
intro_scene = getGameFlag("shiar3", 1 )
if intro_scene == 0
     setEnable("camera_magnet11", "FALSE" )
     startCutScene("FALSE", "FALSE" )
     alive1 = alive("_HERO1_" )
     alive2 = alive("_HERO2_" )
     alive3 = alive("_HERO3_" )
     alive4 = alive("_HERO4_" )
     if alive1 == 1
          setInvisible("_HERO1_", "TRUE" )
     endif
     setNoCollide("_HERO1_", "TRUE" )
     setNoGravity("_HERO1_", "TRUE" )
     copyOriginAndAngles("_HERO1_", "i_hero_spot01" )
     playanim (  "EA_ZONE6", "_HERO1_", "LOOP", "" )
     if alive2 == 1
          setInvisible("_HERO2_", "TRUE" )
     endif
     setNoCollide("_HERO2_", "TRUE" )
     setNoGravity("_HERO2_", "TRUE" )
     copyOriginAndAngles("_HERO2_", "i_hero_spot02" )
     playanim (  "EA_ZONE6", "_HERO2_", "LOOP", "" )
     if alive3 == 1
          setInvisible("_HERO3_", "TRUE" )
     endif
     setNoCollide("_HERO3_", "TRUE" )
     setNoGravity("_HERO3_", "TRUE" )
     copyOriginAndAngles("_HERO3_", "i_hero_spot03" )
     playanim (  "EA_ZONE6", "_HERO3_", "LOOP", "" )
     if alive4 == 1
          setInvisible("_HERO4_", "TRUE" )
     endif
     setNoCollide("_HERO4_", "TRUE" )
     setNoGravity("_HERO4_", "TRUE" )
     copyOriginAndAngles("_HERO4_", "i_hero_spot04" )
     playanim (  "EA_ZONE6", "_HERO4_", "LOOP", "" )
     cameraMove(" 358.620 1512.630 196.460 ", 0.000 )
     cameraPan(" 0.000 85.900 270.700 ", 0.000, "FALSE" )
     waittimed ( 0.250 )
     setGameFlag("shiar3", 1, 1 )
     if alive1 == 1
          setInvisible("_HERO1_", "FALSE" )
     endif
     if alive2 == 1
          setInvisible("_HERO2_", "FALSE" )
     endif
     if alive3 == 1
          setInvisible("_HERO3_", "FALSE" )
     endif
     if alive4 == 1
          setInvisible("_HERO4_", "FALSE" )
     endif
     waittimed ( 0.500 )
     cameraFade(0.000, 1.000 )
     waittimed ( 2.000 )
     startConversation("act4/shiar/shiar3/4_shiar3_010" )
     playanim (  "EA_ZONE6", "_HERO1_", "LOOP", "" )
     playanim (  "EA_ZONE6", "_HERO2_", "LOOP", "" )
     playanim (  "EA_ZONE6", "_HERO3_", "LOOP", "" )
     playanim (  "EA_ZONE6", "_HERO4_", "LOOP", "" )
else
     cameraFade(0.000, 0.000 )
     guns_down = getObjective("Shiar_Obj50", "COMPLETE" )
     dish = getObjective("shiar_obj40", "COMPLETE" )
     waittimed ( 0.100 )
     awardXPToPlayable(5000 )
     sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
     createPopupDialogXml("dialogs/special/guns_achievement" )
     waittimed ( 0.100 )
     if dish == 1
          setEnable("radar_dish_shiar_a_sh01", "FALSE" )
          remove ( "trigger_touch13", "trigger_touch13" )
          remove ( "trigger_touch12", "trigger_touch12" )
          if guns_down == 1
               remove ( "trigger_touch09", "trigger_touch09" )
          endif
     endif
     if guns_down == 1
          remove ( "gun_cam_trigger", "gun_cam_trigger" )
          remove ( "console_gun", "console_gun" )
          remove ( "icon_position_console_1", "icon_position_console_1" )
          remove ( "trigger_touch07", "trigger_touch07" )
          killEntity("gun01" )
          killEntity("gun02" )
          killEntity("gun03" )
          killEntity("gun04" )
          killEntity("gun05" )
          killEntity("gun06" )
          killEntity("gun07" )
          remove ( "gforce_field_a", "gforce_field_a" )
          remove ( "gforce_field_b", "gforce_field_b" )
          remove ( "gforce_field_c", "gforce_field_c" )
          remove ( "gforce_field_d", "gforce_field_d" )
          remove ( "gforce_field_e", "gforce_field_e" )
          remove ( "gforce_field_f", "gforce_field_f" )
          remove ( "big_gun_dome", "big_gun_dome" )
          remove ( "icon_position_gun_1", "icon_position_gun_1" )
          remove ( "icon_position_gun_2", "icon_position_gun_2" )
          remove ( "icon_position_gun_3", "icon_position_gun_3" )
          remove ( "icon_position_gun_4", "icon_position_gun_4" )
          remove ( "icon_position_gun_5", "icon_position_gun_5" )
          remove ( "icon_position_gun_6", "icon_position_gun_6" )
          remove ( "floor_node_shiar_b_sh01", "floor_node_shiar_b_sh01" )
          remove ( "floor_node_shiar_b_sh02", "floor_node_shiar_b_sh02" )
          remove ( "floor_node_shiar_b_sh03", "floor_node_shiar_b_sh03" )
          remove ( "floor_node_shiar_b_sh04", "floor_node_shiar_b_sh04" )
          remove ( "floor_node_shiar_b_sh05", "floor_node_shiar_b_sh05" )
          remove ( "floor_node_shiar_b_sh06", "floor_node_shiar_b_sh06" )
          copyOriginAndAngles("big_gun_broken", "ship_exterior_gun_shiar_b_sh01" )
          waittimed ( 0.100 )
          killEntity("big_gun_broken" )
          remove ( "ship_exterior_gun_shiar_b_sh01", "ship_exterior_gun_shiar_b_sh01" )
     endif
endif

