# Generated by BehavEd
# ( "comment" )
waittimed ( 0.100 )
awardXPToPlayable(5000 )
sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
createPopupDialogXml("dialogs/special/antenna_achievement" )
waittimed ( 0.100 )
obj40 = getObjective("shiar_obj40", "COMPLETE" )
obj50 = getObjective("shiar_obj50", "COMPLETE" )
if obj40 == 1
     if obj50 == 1
          startConversation("act4/shiar/shiar3/corsair_message_both" )
     else
          startConversation("act4/shiar/shiar3/corsair_message_guns" )
     endif
else
     if obj50 == 1
          startConversation("act4/shiar/shiar3/corsair_message_dish" )
     else
          startConversation("act4/shiar/shiar3/corsair_message_neither" )
     endif
endif

