# Generated by BehavEd
# ( "comment" )
waittimed ( 0.100 )
awardXPToPlayable(5000 )
sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
createPopupDialogXml("dialogs/special/omegatrain_achievement" )
waittimed ( 0.100 )
objective ( "Omega_Obj40",  "EOBJCMD_COMPLETE" )

