# Generated by BehavEd
# ( "This script checks if the player has the gizmos" )
got_dampner = getGameFlag("dstark", 5 )
if got_dampner == 1
     awardXPToPlayable(5000 )
     sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
     createPopupDialogXml("dialogs/special/magneticdamp_achievement" )
     waittimed ( 0.100 )
     allowConversation("TRUE" )
else
     allowConversation("FALSE" )
endif

