# Generated by BehavEd
# ( "sets the rubble to be breakable" )
setStructure("column_arch_rubble_r_01_bi_b01", 0 )
setStructure("column_arch_rubble_r_02_bi_b01", 0 )
setStructure("column_arch_rubble_main_bi_b01", 0 )
setStructure("column_arch_rubble_l_02_bi_b01", 0 )
setStructure("column_arch_rubble_l_01_bi_b01", 0 )
waittimed ( 1.000 )
unlockCharacter("SheHulk", "" )
waittimed ( 0.100 )
unlockCharacter("A-Bomb", "" )
waittimed ( 0.100 )
startConversation("act3/bifrost/bifrost2/3_bifrost2_030" )

