# Generated by BehavEd
# ( "comment" )
startCutScene("FALSE", "FALSE" )
act("sp_mysterio_real", "sp_mysterio_real" )
waittimed ( 0.100 )
setInvulnerable("real_m", "TRUE" )
setHintType("ultron_display_omega_a01", "none" )
cameraFocusToEntity("sp_mysterio_real", 350.000, 45.000, 0.000, 2.000 )
waittimed ( 2.000 )
isSpideyhere = isActorOnTeam("spiderman" )
if isSpideyhere == 1
     sound (  "PLAY_SOUND", "common/game/achievement", "", "" )
     createPopupDialogXml("dialogs/special/spidermanmysterio_achievement" )
     waittimed ( 0.100 )
     startConversation("act1/omega/omega3/1_OMEGA3_092" )
else
     startConversation("act1/omega/omega3/1_OMEGA3_090" )
endif

